### PR TITLE
Upgraded gradle wrapper and shadowJar to support openjdk 11.0 on Ubuntu 16.04

### PR DESCRIPTION
**Pull request by udif**

### CODE REVIEW

**Comment by udif** [comment]
A new unrelated pull request accidentally got appended here because I pushed both to my dev branch.

**Comment by sdnellen** [comment]
will follow up on this when i have a chance to review in more detail - need to give this some thought.  In general, if tool is going to integrate preprocessors, would like to allow for selection of type to be used and provide a general mechanism (and enable no preprocessing by default as this is current behavior and significant number of users are preprocessing externally).  Also, would be desired to have preprocessing apply to all input types, not just rdl as most are generally applicable.

**Comment by udif** [comment]
That's OK. You can cherry-pick the Ubuntu upgrade. the preprocessor commit got into the pull request by mistake as I've used a single dev branch and had no idea a pull request would automatically pull the branch head.
If you want I can send a new pull request with a dedicated branch just for the gradle changes.

**Comment by sdnellen** [comment]
yes, pls create a clean pr with just the gradle mods (and confirm changes to gradle.bat are just the license header - think diff is picking up line end deltas).

**Pull request closed without merging**
